using FMODUtilityPackage.Core;

namespace FMODUtilityPackage.Enums
{
    // ReSharper disable InconsistentNaming
    /// <summary>
    ///     All FMOD events, these are automatically generated by the <see cref="AudioManager" />
    /// </summary>
    public enum
        AudioEventType // Automatically generated from FMOD events, do not edit! (Open the AudioManager inspector or use the "FMOD/Import Events" menu to regenerate)
    {
	    /// <FMODEventPath>
	    ///     event:/Music/Battle
	    /// </FMODEventPath>
	    Music_Battle,

	    /// <FMODEventPath>
	    ///     event:/Music/Hell
	    /// </FMODEventPath>
	    Music_Hell,

	    /// <FMODEventPath>
	    ///     event:/Music/QuirkyCat
	    /// </FMODEventPath>
	    Music_QuirkyCat,

	    /// <FMODEventPath>
	    ///     event:/Music/Finalboss
	    /// </FMODEventPath>
	    Music_Finalboss,

	    /// <FMODEventPath>
	    ///     event:/Music/BattleVictory
	    /// </FMODEventPath>
	    Music_BattleVictory,

	    /// <FMODEventPath>
	    ///     event:/SFX/Battle/HitEnemy
	    /// </FMODEventPath>
	    SFX_Battle_HitEnemy,

	    /// <FMODEventPath>
	    ///     event:/SFX/UI/ButtonWrong
	    /// </FMODEventPath>
	    SFX_UI_ButtonWrong,

	    /// <FMODEventPath>
	    ///     event:/SFX/Battle/MissAttack
	    /// </FMODEventPath>
	    SFX_Battle_MissAttack,

	    /// <FMODEventPath>
	    ///     event:/SFX/Battle/MageSpells/Shower
	    /// </FMODEventPath>
	    SFX_Battle_MageSpells_Shower,

	    /// <FMODEventPath>
	    ///     event:/SFX/Battle/MageSpells/Furrball
	    /// </FMODEventPath>
	    SFX_Battle_MageSpells_Furrball,

	    /// <FMODEventPath>
	    ///     event:/SFX/Battle/SuperStrongPowerDowerSlam
	    /// </FMODEventPath>
	    SFX_Battle_SuperStrongPowerDowerSlam,

	    /// <FMODEventPath>
	    ///     event:/SFX/Battle/MageSpells/Hairdryer
	    /// </FMODEventPath>
	    SFX_Battle_MageSpells_Hairdryer,

	    /// <FMODEventPath>
	    ///     event:/SFX/Battle/TankBuff
	    /// </FMODEventPath>
	    SFX_Battle_TankBuff,

	    /// <FMODEventPath>
	    ///     event:/SFX/Battle/PlayerHurt
	    /// </FMODEventPath>
	    SFX_Battle_PlayerHurt,

	    /// <FMODEventPath>
	    ///     event:/SFX/Battle/MageSpells/SupersonicMeow
	    /// </FMODEventPath>
	    SFX_Battle_MageSpells_SupersonicMeow,

	    /// <FMODEventPath>
	    ///     event:/SFX/Battle/MageSpells/MagicSuperSmack
	    /// </FMODEventPath>
	    SFX_Battle_MageSpells_MagicSuperSmack,

	    /// <FMODEventPath>
	    ///     event:/SFX/UI/ButtonClick
	    /// </FMODEventPath>
	    SFX_UI_ButtonClick,

	    /// <FMODEventPath>
	    ///     event:/SFX/Player/Footsteps
	    /// </FMODEventPath>
	    SFX_Player_Footsteps,

	    /// <FMODEventPath>
	    ///     event:/SFX/Battle/SwordAttack
	    /// </FMODEventPath>
	    SFX_Battle_SwordAttack,

	    /// <FMODEventPath>
	    ///     event:/SFX/UI/ButtonHover
	    /// </FMODEventPath>
	    SFX_UI_ButtonHover,

	    /// <FMODEventPath>
	    ///     event:/SFX/Ambience/HellAmbience
	    /// </FMODEventPath>
	    SFX_Ambience_HellAmbience,

	    /// <FMODEventPath>
	    ///     event:/SFX/UI/Talking
	    /// </FMODEventPath>
	    SFX_UI_Talking,

	    /// <FMODEventPath>
	    ///     event:/SFX/Cutscenes/Scene6
	    /// </FMODEventPath>
	    SFX_Cutscenes_Scene6,

	    /// <FMODEventPath>
	    ///     event:/SFX/Cutscenes/Scene1
	    /// </FMODEventPath>
	    SFX_Cutscenes_Scene1,

	    /// <FMODEventPath>
	    ///     event:/SFX/Cutscenes/Scene8
	    /// </FMODEventPath>
	    SFX_Cutscenes_Scene8,

	    /// <FMODEventPath>
	    ///     event:/SFX/Battle/Death
	    /// </FMODEventPath>
	    SFX_Battle_Death
    }
}